#!/bin/bash

set -euo pipefail

# WezTerm config, one of two modes depending on where WezTerm runs. In both,
# this repo's wezterm/wezterm.lua stays the single source of truth — edit it
# and reload WezTerm (Ctrl+Shift+R).
#
# * Windows + WSL: WezTerm is a Windows GUI app, so (unlike tmux/nvim) its
#   config can't be symlinked into the Linux home — it must live where Windows
#   WezTerm looks: %USERPROFILE%\.config\wezterm\wezterm.lua. Creating a
#   directory symlink there would need Windows Developer Mode (off by default)
#   or admin rights. Instead we write a tiny *bootstrap* file on the Windows
#   side that dofile()s the REAL config from this repo over the WSL UNC path.
#   No admin needed.
#
# * Native Linux: WezTerm reads ~/.config/wezterm/wezterm.lua directly, so a
#   plain symlink into the repo is all it takes.

repo_wezterm="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Windows home as a /mnt/c path we can write to, e.g. /mnt/c/Users/WELCOME.
# Empty when cmd.exe isn't reachable — i.e. not running under WSL interop.
# (`|| true` keeps set -e from killing the script on that failure.)
userprofile="$(cmd.exe /c 'echo %USERPROFILE%' 2>/dev/null | tr -d '\r' || true)"

if [[ -z "$userprofile" ]]; then
    cfg="$HOME/.config/wezterm/wezterm.lua"
    if [ -e "$cfg" ] && [ ! -L "$cfg" ]; then
        echo "[wezterm] $cfg already exists as a real file, skipping symlink." >&2
        exit 0
    fi
    mkdir -p "$(dirname "$cfg")"
    ln -sfnT "$repo_wezterm/wezterm.lua" "$cfg"
    echo "[wezterm] Symlinked $cfg -> $repo_wezterm/wezterm.lua"
    exit 0
fi

wsl_home="$(wslpath -u "$userprofile")"
cfg_dir="$wsl_home/.config/wezterm"

# UNC path of this repo's wezterm dir, e.g. \\wsl.localhost\Ubuntu-24.04\...\wezterm
repo_unc="$(wslpath -w "$repo_wezterm")"
# Escape backslashes for a Lua string literal.
lua_repo="${repo_unc//\\/\\\\}"

mkdir -p "$cfg_dir"

# Bootstrap Lua: load the repo config over UNC. package.path is prepended with
# the repo dir so future require("...") of sibling modules also resolves there.
# printf '%s' preserves backslashes verbatim in each argument.
printf '%s\n' \
    '-- AUTO-GENERATED by dev-environment-setup/wezterm/install.sh — do not edit here.' \
    '-- Loads the real config from the repo over the WSL UNC path, so the repo stays' \
    '-- the single source of truth (no admin / Developer-Mode symlink needed).' \
    '-- Re-run install.sh if you move the repo.' \
    "local repo = \"${lua_repo}\"" \
    'package.path = package.path .. ";" .. repo .. "\\?.lua;" .. repo .. "\\?\\init.lua"' \
    'return dofile(repo .. "\\wezterm.lua")' \
    > "$cfg_dir/wezterm.lua"

echo "[wezterm] Wrote bootstrap config: ${cfg_dir}/wezterm.lua"
echo "[wezterm]   -> loads ${repo_unc}\\wezterm.lua"
echo "[wezterm] (Re)start WezTerm; Ctrl+Shift+R reloads after edits to the repo config."
